---
# tasks file for roles/rhosp_director
- name: install several packages
  yum:
    name: "{{ director_packages_install }}"
    state: latest
  tags: package

- name: remove several packages
  yum:
    name: "{{ director_packages_remove }}"
    state: absent
  tags: package

- name: Enable Services
  systemd:
    name: "{{ services_enable }}"
    state: started
  tags: service

- name: Disable Services
  systemd:
    name: "{{ services_disable }}"
    state: stopped
  tags: service

- name: Change Various Sysctl-Settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'
